'use strict';
const fs = require('node:fs'); const path = require('node:path');
function dailySummary(db, date) {
  const events = db.prepare('SELECT * FROM events WHERE created_at LIKE ? ORDER BY created_at ASC').all(`${date}%`);
  const lines = [`# TeamBrain daily view — ${date}`, '', `Generated from ${events.length} canonical event(s). Do not edit this file; regenerate it.`, ''];
  if (!events.length) lines.push('_No events recorded._');
  for (const event of events) { lines.push(`## ${event.title}`, '', `- Time: ${event.created_at}`, `- Actor: ${event.actor_id}`, `- Type: ${event.event_type}`, `- Source: ${event.source}`, ''); if (event.body) lines.push(event.body, ''); }
  return lines.join('\n');
}
function writeDailyView(root, date, contents) { const file = path.join(root, '.teambrain', 'views', 'daily', `${date}.md`); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, contents); return file; }
module.exports = { dailySummary, writeDailyView };
