'use strict';
const fs = require('node:fs'); const path = require('node:path'); const os = require('node:os'); const crypto = require('node:crypto'); const { spawnSync } = require('node:child_process');
const ALLOWED = new Set(['.txt', '.md', '.csv', '.tsv', '.json', '.log', '.docx', '.xlsx', '.xlsm', '.pdf']);
const PLAIN_TEXT = new Set(['.txt', '.md', '.csv', '.tsv', '.json', '.log']);
function slug(value) { return String(value).toLowerCase().replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').slice(0, 80) || 'belge'; }
function decodeText(buffer) { for (const encoding of ['utf-8', 'windows-1254', 'windows-1252']) { try { return new TextDecoder(encoding, { fatal: true }).decode(buffer).replace(/^\uFEFF/, ''); } catch {} } return buffer.toString('utf8'); }
function extract(file) { const script = path.join(__dirname, 'document-extractor.py'); for (const command of ['python', 'python3']) { try { const output = spawnSync(command, [script, file], { encoding: 'utf8', maxBuffer: 20 * 1024 * 1024 }); const data = JSON.parse(output.stdout || '{}'); if (output.error && output.error.code === 'ENOENT') continue; if (output.status !== 0 || data.error) throw new Error(data.error || 'Metin çıkarılamadı.'); return data; } catch (error) { if (!/not found|ENOENT/i.test(String(error))) throw error; } } throw new Error('Python 3 bulunamadı.'); }
function importDocument(root, input) { const filename = String(input.filename || '').trim(); const ext = path.extname(filename).toLowerCase(); if (!filename || filename.length > 180 || !ALLOWED.has(ext)) throw new Error('Bu dosya türü desteklenmiyor.'); const buffer = Buffer.isBuffer(input.data) ? input.data : Buffer.from(input.data || []); if (!buffer.length || buffer.length > 15 * 1024 * 1024) throw new Error('Dosya boş olamaz ve 15 MB sınırını aşamaz.'); let result; if (PLAIN_TEXT.has(ext)) { const text = decodeText(buffer).replace(/\x00/g, '').trim(); result = { text, characters: text.length }; } else { const temp = path.join(os.tmpdir(), `teambrain-${crypto.randomUUID()}${ext}`); fs.writeFileSync(temp, buffer); try { result = extract(temp); } finally { try { fs.unlinkSync(temp); } catch {} } } if (!result.text) throw new Error('Dosyadan okunabilir metin çıkarılamadı.'); const id = crypto.randomUUID(); const sha256 = crypto.createHash('sha256').update(buffer).digest('hex'); const relative = path.join('memory', 'knowledge', 'imports', `${id}-${slug(path.basename(filename, ext))}.md`); const target = path.join(root, relative); fs.mkdirSync(path.dirname(target), { recursive: true }); const content = `---\nschema_version: 1\ndocument_id: ${id}\nproject_id: ${input.project_id}\nsource_filename: ${JSON.stringify(filename)}\nsource_sha256: ${sha256}\nimported_at: ${new Date().toISOString()}\n---\n\n# ${filename.replace(/[#\r\n]/g, ' ')}\n\n> Bu kayıt TeamBrain belge aktarımıyla oluşturuldu. Orijinal dosya varsayılan olarak saklanmadı.\n\n${result.text}\n`; fs.writeFileSync(target, content, { flag: 'wx' }); return { document_id: id, filename, file: relative.replace(/\\/g, '/'), sha256, characters: result.characters }; }
function listDocuments(root) { const base = path.join(root, 'memory', 'knowledge', 'imports'); if (!fs.existsSync(base)) return []; return fs.readdirSync(base).filter(file => file.endsWith('.md')).map(file => ({ file: path.join('memory', 'knowledge', 'imports', file).replace(/\\/g, '/') })); }
module.exports = { importDocument, listDocuments };
